GET https://localhost:7108/api/Products
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjdiMTZlMzM3LTA5MjQtNDFkZC1iYzUyLWMxMDJhYzk2ZjVhYyIsIlVzZXJOYW1lIjoidGFuZXIiLCJFbWFpbCI6InRhbmVyc2F5ZGFtQGdtYWlsLmNvbSIsIm5iZiI6MTcyMjE1NTMxMywiZXhwIjoxNzIyMTU4OTEzLCJpc3MiOiJUYW5lciBTYXlkYW0iLCJhdWQiOiJNYWhtdXQgRGVtaXJraXJhbixNZWhtZXQgT3p0ZW1lbCJ9.gc0p27vECzdotnHIF-iyA-5SR35uOFxLELc0fUtST1K9o7ib7AgI0xbcgU6allbSqUicdek9D9lsilrgYhifaA

###
